# Generated by Django 4.2.5 on 2023-11-22 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_wishlist_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user/person.png', upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 7, 12, 29, 273791, tzinfo=datetime.timezone.utc)),
        ),
    ]
