# Generated by Django 4.2.5 on 2023-11-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_image_alter_cart_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
    ]
