# Generated by Django 4.2.5 on 2023-11-28 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_cart_date_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 8, 43, 26, 744053, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
