# Generated by Django 4.2.5 on 2023-11-28 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_cart_date_alter_cart_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 11, 14, 6, 239217, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 11, 14, 6, 239217, tzinfo=datetime.timezone.utc)),
        ),
    ]
