# Generated by Django 4.2.5 on 2023-12-16 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_cart_date_alter_cart_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 10, 8, 34, 151055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 10, 8, 34, 151055, tzinfo=datetime.timezone.utc)),
        ),
    ]
