# Generated by Django 5.0 on 2023-12-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('lsbn', models.CharField(max_length=200)),
                ('Publisher', models.CharField(max_length=200)),
            ],
        ),
    ]
